[package]
name = "codegen"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
tera = "1.19"
serde = { version = "1", features = ["derive"] }
syn = { version = "2.0", features = ["full", "parsing"] }
quote = "1.0"
